trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64|ARM|ARM64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\CustomThemesPackage\Package.appxmanifest
      $xmlDoc.Package.Identity.Name="49306atecsolution.ThemesforFiles"
      $xmlDoc.Save('$(Build.SourcesDirectory)\CustomThemesPackage\Package.appxmanifest')
    failOnStderr: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'

- task: store-publish@0
  inputs:
    serviceEndpoint: 'Files'
    appId: '9N20KQ61LSFQ'
    packagePath: '$(appxPackageDir)\**\*.msixupload'
    force: true
    skipPolling: true
    deletePackages: true
    numberOfPackagesToKeep: '3'
